import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config();

const client = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
});

export const askAI = async (req, res) => {
  try {
    const { message } = req.body;

    // Validation
    if (!message || message.trim() === "") {
      return res.status(400).json({
        error: "Message is required",
      });
    }

    const completion = await client.chat.completions.create({
      // Replace with whichever free model works in your account
      model:"openrouter/free",

      messages: [
        {
          role: "system",
          content: `
You are a professional nutritionist and fitness coach for the LET'S DIET application.

Rules:
- Answer only diet, nutrition, fitness and health related questions.
- Keep responses practical and safe.
- Never recommend dangerous diets.
- Use proper markdown formatting.
- Put headings on separate lines.
- Add one blank line after headings.
- Use bullet points only.
- Never use markdown tables.
- Keep responses mobile friendly.

Correct format:

## Breakfast

- Oats
- Banana
- Milk

## Lunch

- Rice
- Lentils
- Salad

Return ONLY markdown.
`,
        },
        {
          role: "user",
          content: message,
        },
      ],

      max_tokens: 700,
      temperature: 0.7,
    });

    let aiResponse = completion.choices[0].message.content || "";

aiResponse = aiResponse

  // Put headings on their own lines
  .replace(/##\s([^#\n-]+)\s-\s/g, "## $1\n\n- ")

  // Ensure headings start on new line
  .replace(/(##\s.*?)(?=##|$)/gs, (match) => {
    return match.replace(/ - /g, "\n- ");
  })

  // Remove excessive empty lines
  .replace(/\n{3,}/g, "\n\n")

  .trim();

    if (!aiResponse) {
      return res.status(500).json({
        error: "No response generated by AI.",
      });
    }

    return res.status(200).json({
      response: aiResponse,
    });

  } catch (error) {
    console.log("OPENROUTER ERROR:");
    console.log(error);

    return res.status(500).json({
      error:
        error?.error?.message ||
        error?.message ||
        "Failed to generate AI response",
    });
  }
};